language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: true
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    
script:
    - platformio lib install
    - cd /home/travis/build/DiegoTheWolf/EMTB
    - ls 
    - platformio run -d /home/travis/build/DiegoTheWolf/EMTB/EMTB_RX

notifications:
  email:
    on_success: never
    on_failure: never
