language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: true
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=EMTB_RX/src
    
install:
    - pip install -U platformio
    - wget https://github.com/DiegoTheWolf/EMTB/archive/DEV_Online.zip -O /tmp/mylib.zip
    - unzip /tmp/mylib.zip -d /tmp
#    - cd /tmp/EMTB-DEV_Online/libraries/
    - mv /tmp/EMTB-DEV_Online/libraries/* ../../

script:
    - platformio ci --board=pro8MHzatmega328

notifications:
  email:
    on_success: never
    on_failure: never
