language: c

before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  - ln -s $PWD /usr/local/share/arduino/libraries/Bounce2
  - ln -s $PWD /usr/local/share/arduino/libraries/RF24
  - ln -s $PWD /usr/local/share/arduino/libraries/TFT_ST7735
  - ln -s $PWD /usr/local/share/arduino/libraries/VescUartControl
  - arduino --install-library "Bounce2, RF24, TFT_ST7735, VescUartControl"
script:
  - arduino --verify --board ${BOARD} $PWD/EMTB_RX/src/EMTB_RX.cpp
  - arduino --verify --board ${BOARD} $PWD/EMTB_TX/src/EMTB_TX.cpp
notifications:
  email:
    on_success: change
    on_failure: change
    
env:
# - BOARD=arduino:avr:uno
# - BOARD=arduino:avr:yun
# - BOARD=arduino:avr:diecimila:cpu=atmega168
# - BOARD=arduino:avr:diecimila:cpu=atmega328
# - BOARD=arduino:avr:nano:cpu=atmega168
# - BOARD=arduino:avr:nano:cpu=atmega328
# - BOARD=arduino:avr:mega:cpu=atmega1280
# - BOARD=arduino:avr:mega:cpu=atmega2560
# - BOARD=arduino:avr:megaADK
# - BOARD=arduino:avr:leonardo
# - BOARD=arduino:avr:micro
# - BOARD=arduino:avr:esplora
# - BOARD=arduino:avr:mini:cpu=atmega168
# - BOARD=arduino:avr:mini:cpu=atmega328
# - BOARD=arduino:avr:ethernet
# - BOARD=arduino:avr:bt:cpu=atmega168
# - BOARD=arduino:avr:bt:cpu=atmega328
# - BOARD=arduino:avr:lilypad:cpu=atmega168
# - BOARD=arduino:avr:lilypad:cpu=atmega328
# - BOARD=arduino:avr:pro:cpu=atmega168
 - BOARD=arduino:avr:pro:cpu=atmega328
# - BOARD=arduino:sam:arduino_due_x
